2025-08-11 14:46:35,739 - INFO - Running strategy for /ES at 2025-08-11 07:46:35.739835-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 14:46:35,771 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 14:46:37,246 - ERROR - Error in strategy for /ES: configure_logger() missing 1 required positional argument: 'strategy'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 385, in get_historical_and_live_data
    df = get_historical_data(ticker, timeframe, logger, strategy)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 92, in get_historical_data
    return get_tick_based_historical_data(ticker, timeframe, logger, redis_client, db_api_key, dataset, strategy)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 108, in get_tick_based_historical_data
    tick_buffer = TickDataBufferWithRedis(
        ticker=ticker_for_data,
    ...<4 lines>...
        strategy=strategy
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 18, in __init__
    super().__init__(ticker, tick_size, db_api_key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\tick_buffer.py", line 19, in __init__
    self.logger = configure_logger(ticker)
                  ~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: configure_logger() missing 1 required positional argument: 'strategy'
2025-08-11 14:46:37,462 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 15:10:27,815 - INFO - Running strategy for /ES at 2025-08-11 08:10:27.815418-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 15:10:27,881 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 15:10:30,471 - ERROR - Error in strategy for /ES: name 'tick_buffer' is not defined
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 228, in get_historical_and_live_data
    df = get_historical_data(ticker, timeframe, logger, strategy)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 48, in get_historical_data
    return get_tick_based_historical_data(ticker, timeframe, logger, redis_client, db_api_key, dataset, strategy)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 84, in get_tick_based_historical_data
    tick_buffer.warmup_with_historical_ticks(
    ^^^^^^^^^^^
NameError: name 'tick_buffer' is not defined
2025-08-11 15:10:30,644 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 15:14:52,544 - INFO - Running strategy for /ES at 2025-08-11 08:14:52.544838-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 15:14:52,545 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 15:14:55,427 - ERROR - Error in strategy for /ES: name 'tick_buffer' is not defined
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 228, in get_historical_and_live_data
    df = get_historical_data(ticker, timeframe, logger, strategy)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 48, in get_historical_data
    return get_tick_based_historical_data(ticker, timeframe, logger, redis_client, db_api_key, dataset, strategy)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 84, in get_tick_based_historical_data
    tick_buffer.warmup_with_historical_ticks(
    ^^^^^^^^^^^
NameError: name 'tick_buffer' is not defined
2025-08-11 15:14:55,587 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 18:16:59,435 - INFO - Running strategy for /ES at 2025-08-11 11:16:59.435774-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 18:16:59,437 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 18:17:03,916 - ERROR - Error in strategy for /ES: warmup_with_historical_ticks() missing 6 required positional arguments: 'dataset', 'start', 'end', 'logger', 'tick_size', and 'create_bar_from_ticks_fn'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 287, in get_historical_and_live_data
    warmup_with_historical_ticks(ticker_for_data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: warmup_with_historical_ticks() missing 6 required positional arguments: 'dataset', 'start', 'end', 'logger', 'tick_size', and 'create_bar_from_ticks_fn'
2025-08-11 18:17:04,116 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 20:02:11,853 - INFO - Running strategy for /ES at 2025-08-11 13:02:11.853583-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 20:02:11,869 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 20:02:13,802 - ERROR - Error in strategy for /ES: module 'threading' has no attribute 'lock'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 124, in get_historical_and_live_data
    lock = threading.lock()
           ^^^^^^^^^^^^^^
AttributeError: module 'threading' has no attribute 'lock'. Did you mean: 'Lock'?
2025-08-11 20:02:13,981 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 20:05:48,088 - INFO - Running strategy for /ES at 2025-08-11 13:05:48.088659-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 20:05:48,090 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 20:05:50,732 - ERROR - Error in strategy for /ES: module 'threading' has no attribute 'lock'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 124, in get_historical_and_live_data
    lock = threading.lock()
           ^^^^^^^^^^^^^^
AttributeError: module 'threading' has no attribute 'lock'. Did you mean: 'Lock'?
2025-08-11 20:05:50,893 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 20:06:11,282 - INFO - Running strategy for /ES at 2025-08-11 13:06:11.282813-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 20:06:11,283 - INFO - Attempting to connect to Redis at localhost:6379 db=0
2025-08-11 20:06:13,535 - ERROR - Error in strategy for /ES: module 'threading' has no attribute 'lock'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 123, in get_historical_and_live_data
    lock = threading.lock()
           ^^^^^^^^^^^^^^
AttributeError: module 'threading' has no attribute 'lock'. Did you mean: 'Lock'?
2025-08-11 20:06:13,729 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:18:22,167 - INFO - Running strategy for /ES at 2025-08-11 14:18:22.167324-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:18:25,318 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:20:17,921 - INFO - Running strategy for /ES at 2025-08-11 14:20:17.921892-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:20:20,225 - ERROR - Error in strategy for /ES: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 82, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 65, in get_historical_start_time
    start_time = (end_time - timedelta(days=1)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:20:20,560 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:20:34,652 - INFO - Running strategy for /ES at 2025-08-11 14:20:34.652733-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:20:34,652 - INFO - Running strategy for /ES at 2025-08-11 14:20:34.652733-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:20:37,226 - ERROR - Error in strategy for /ES: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 82, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 65, in get_historical_start_time
    start_time = (end_time - timedelta(days=1)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:20:37,226 - ERROR - Error in strategy for /ES: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 82, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 65, in get_historical_start_time
    start_time = (end_time - timedelta(days=1)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:20:37,663 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:20:37,663 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:21:03,428 - INFO - Running strategy for /ES at 2025-08-11 14:21:03.427908-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:21:05,578 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:21:30,711 - INFO - Running strategy for /ES at 2025-08-11 14:21:30.711330-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:21:32,956 - ERROR - Error in strategy for /ES: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 82, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 74, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 65, in get_historical_start_time
    start_time = (end_time - timedelta(days=1)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:21:33,117 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:33:00,588 - INFO - Running strategy for /ES at 2025-08-11 14:33:00.587990-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:33:02,990 - ERROR - Error in strategy for /ES: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 98, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 87, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 66, in get_historical_start_time
    start_time = (end_time - timedelta(days=1)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:33:03,326 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:33:33,425 - INFO - Running strategy for /ES at 2025-08-11 14:33:33.425595-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:33:36,051 - ERROR - Error in strategy for /ES: extract_tick_count() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 98, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 90, in get_historical_data
    tick_size = extract_tick_count(timeframe, dataset)
TypeError: extract_tick_count() takes 1 positional argument but 2 were given
2025-08-11 21:33:36,353 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:34:25,088 - INFO - Running strategy for /ES at 2025-08-11 14:34:25.088936-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:34:27,478 - ERROR - Error in strategy for /ES: extract_tick_count() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 99, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 91, in get_historical_data
    tick_size = extract_tick_count(timeframe, dataset)
TypeError: extract_tick_count() takes 1 positional argument but 2 were given
2025-08-11 21:34:27,635 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:34:58,454 - INFO - Running strategy for /ES at 2025-08-11 14:34:58.454936-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:35:01,501 - ERROR - Error in strategy for /ES: extract_tick_count() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 100, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 92, in get_historical_data
    tick_size = extract_tick_count(timeframe, dataset)
TypeError: extract_tick_count() takes 1 positional argument but 2 were given
2025-08-11 21:35:01,804 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:35:38,195 - INFO - Running strategy for /ES at 2025-08-11 14:35:38.195929-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:35:41,756 - ERROR - Error in strategy for /ES: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESU5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 98, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 91, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, symbol)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 71, in get_tick_based_data
    data = DATABENTO_CLIENT.timeseries.get_range(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        dataset=dataset,
        ^^^^^^^^^^^^^^^^
    ...<5 lines>...
        limit=tick_size
        ^^^^^^^^^^^^^^^
    ).to_df()
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESU5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
2025-08-11 21:35:42,051 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:36:04,943 - INFO - Running strategy for /ES at 2025-08-11 14:36:04.943250-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:36:09,250 - ERROR - Error in strategy for /ES: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESU5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 99, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 92, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, symbol)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 71, in get_tick_based_data
    data = DATABENTO_CLIENT.timeseries.get_range(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        dataset=dataset,
        ^^^^^^^^^^^^^^^^
    ...<5 lines>...
        limit=tick_size
        ^^^^^^^^^^^^^^^
    ).to_df()
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESU5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
2025-08-11 21:36:09,405 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:37:18,299 - INFO - Running strategy for /ES at 2025-08-11 14:37:18.299008-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:37:23,364 - ERROR - Error in strategy for /ES: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESU5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 99, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 92, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, symbol)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 71, in get_tick_based_data
    data = DATABENTO_CLIENT.timeseries.get_range(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        dataset=dataset,
        ^^^^^^^^^^^^^^^^
    ...<5 lines>...
        limit=tick_size
        ^^^^^^^^^^^^^^^
    ).to_df()
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESU5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
2025-08-11 21:37:23,624 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:38:23,672 - INFO - Running strategy for /ES at 2025-08-11 14:38:23.672277-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:38:27,338 - ERROR - Error in strategy for /ES: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESU5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 99, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 92, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, symbol)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 72, in get_tick_based_data
    data = DATABENTO_CLIENT.timeseries.get_range(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        dataset=dataset,
        ^^^^^^^^^^^^^^^^
    ...<5 lines>...
        limit=tick_size
        ^^^^^^^^^^^^^^^
    ).to_df()
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESU5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
2025-08-11 21:38:27,658 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:38:44,315 - INFO - Running strategy for /ES at 2025-08-11 14:38:44.315562-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:38:47,867 - ERROR - Error in strategy for /ES: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESU5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 99, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 92, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, symbol)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 71, in get_tick_based_data
    data = DATABENTO_CLIENT.timeseries.get_range(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        dataset=dataset,
        ^^^^^^^^^^^^^^^^
    ...<5 lines>...
        limit=tick_size
        ^^^^^^^^^^^^^^^
    ).to_df()
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESU5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
2025-08-11 21:38:48,021 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:39:11,042 - INFO - Running strategy for /ES at 2025-08-11 14:39:11.042190-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:39:14,526 - ERROR - Error in strategy for /ES: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESU5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 107, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 100, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, symbol)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 71, in get_tick_based_data
    data = DATABENTO_CLIENT.timeseries.get_range(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        dataset=dataset,
        ^^^^^^^^^^^^^^^^
    ...<5 lines>...
        limit=tick_size
        ^^^^^^^^^^^^^^^
    ).to_df()
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESU5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
2025-08-11 21:39:14,791 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:41:42,569 - INFO - Running strategy for /ES at 2025-08-11 14:41:42.569850-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:41:45,633 - ERROR - Error in strategy for /ES: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 99, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 88, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 66, in get_historical_start_time
    start_time = (end_time - timedelta(days=1)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:41:45,908 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:43:31,654 - INFO - Running strategy for /ES at 2025-08-11 14:43:31.654243-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:43:35,759 - ERROR - Error in strategy for /ES: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 100, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 89, in get_historical_data
    start_time = get_historical_start_time(timeframe, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 66, in get_historical_start_time
    start_time = (end_time - timedelta(days=1)).isoformat()
                  ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.timedelta'
2025-08-11 21:43:35,924 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:45:49,973 - INFO - Running strategy for /ES at 2025-08-11 14:45:49.973659-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:45:54,009 - ERROR - Error in strategy for /ES: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESU5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 101, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 94, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, symbol)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 71, in get_tick_based_data
    data = DATABENTO_CLIENT.timeseries.get_range(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        dataset=dataset,
        ^^^^^^^^^^^^^^^^
    ...<5 lines>...
        limit=tick_size
        ^^^^^^^^^^^^^^^
    ).to_df()
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESU5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
2025-08-11 21:45:54,163 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:48:07,779 - INFO - Running strategy for /ES at 2025-08-11 14:48:07.779816-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:48:17,981 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:51:24,931 - INFO - Running strategy for /ES at 2025-08-11 14:51:24.931559-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:51:36,187 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:53:18,422 - INFO - Running strategy for /ES at 2025-08-11 14:53:18.422002-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:53:32,012 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:55:16,798 - INFO - Running strategy for /ES at 2025-08-11 14:55:16.798316-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:55:26,850 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 21:56:30,190 - INFO - Running strategy for /ES at 2025-08-11 14:56:30.190066-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 21:56:33,793 - ERROR - Error in strategy for /ES: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESU5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 99, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 94, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, symbol)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 72, in get_tick_based_data
    data = DATABENTO_CLIENT.timeseries.get_range(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        dataset=dataset,
        ^^^^^^^^^^^^^^^^
    ...<5 lines>...
        limit=tick_size
        ^^^^^^^^^^^^^^^
    ).to_df()
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESU5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
2025-08-11 21:56:33,954 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:01:22,035 - INFO - Running strategy for /ES at 2025-08-11 15:01:22.035781-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:01:26,115 - ERROR - Error in strategy for /ES: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESH5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 99, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 94, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, symbol)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 72, in get_tick_based_data
    data = DATABENTO_CLIENT.timeseries.get_range(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        dataset=dataset,
        ^^^^^^^^^^^^^^^^
    ...<5 lines>...
        limit=100
        ^^^^^^^^^
    ).to_df()
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESH5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
2025-08-11 22:01:26,476 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:01:44,193 - INFO - Running strategy for /ES at 2025-08-11 15:01:44.193769-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:01:48,354 - ERROR - Error in strategy for /ES: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESH5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 99, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 94, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, symbol)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 72, in get_tick_based_data
    data = DATABENTO_CLIENT.timeseries.get_range(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        dataset=dataset,
        ^^^^^^^^^^^^^^^^
    ...<5 lines>...
        # limit=100
        ^^^^^^^^^^^
    ).to_df()
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 400 symbology_invalid_symbol
Invalid format for `continuous` symbol 'ESH5', expected format: '[ROOT].[ROLL_RULE].[RANK]'.
documentation: https://databento.com/docs/api-reference-historical/basics/symbology
2025-08-11 22:01:48,689 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:02:01,841 - INFO - Running strategy for /ES at 2025-08-11 15:02:01.841687-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:02:08,532 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:04:14,462 - INFO - Running strategy for /ES at 2025-08-11 15:04:14.462627-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:04:16,278 - ERROR - Error in strategy for /ES: 'MetadataHttpAPI' object has no attribute 'list_symbols'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 100, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 95, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, symbol)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 72, in get_tick_based_data
    print(DATABENTO_CLIENT.metadata.list_symbols(dataset=dataset).head())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MetadataHttpAPI' object has no attribute 'list_symbols'
2025-08-11 22:04:16,960 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:04:48,933 - INFO - Running strategy for /ES at 2025-08-11 15:04:48.933414-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:04:51,734 - ERROR - Error in strategy for /ES: 'MetadataHttpAPI' object has no attribute 'list_symbols'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 100, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 95, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, symbol)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 72, in get_tick_based_data
    print(DATABENTO_CLIENT.metadata.list_symbols(dataset=dataset).head())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MetadataHttpAPI' object has no attribute 'list_symbols'
2025-08-11 22:04:51,891 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:27:17,857 - INFO - Running strategy for /ES at 2025-08-11 15:27:17.857768-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:27:24,421 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:32:20,880 - INFO - Running strategy for /ES at 2025-08-11 15:32:20.880810-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:32:24,887 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:36:15,082 - INFO - Running strategy for /ES at 2025-08-11 15:36:15.082387-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:36:25,256 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 22:37:53,931 - INFO - Running strategy for /ES at 2025-08-11 15:37:53.931700-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 22:38:03,782 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:04:07,318 - INFO - Running strategy for /ES at 2025-08-11 16:04:07.318024-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:04:11,886 - ERROR - Error in strategy for /ES: name 'start' is not defined
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 119, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 113, in get_historical_data
    instrument_id = symbology_resolve(dataset, symbol, start, end)
                                                       ^^^^^
NameError: name 'start' is not defined
2025-08-11 23:04:12,040 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:04:42,590 - INFO - Running strategy for /ES at 2025-08-11 16:04:42.590304-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:05:09,573 - INFO - Running strategy for /ES at 2025-08-11 16:05:09.573002-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:05:31,027 - ERROR - Error fetching historical end time for dataset GLBX.MDP3: HTTPSConnectionPool(host='hist.databento.com', port=443): Max retries exceeded with url: /v0/metadata.get_dataset_range?dataset=GLBX.MDP3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000207FA58EAD0>, 'Connection to hist.databento.com timed out. (connect timeout=100)'))
2025-08-11 23:05:31,027 - ERROR - Error in strategy for /ES: name 'datetime' is not defined
Traceback (most recent call last):
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
        (self._dns_host, self.port),
    ...<2 lines>...
        socket_options=self.socket_options,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 704, in connect
    self.sock = sock = self._new_conn()
                       ~~~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 207, in _new_conn
    raise ConnectTimeoutError(
    ...<2 lines>...
    ) from e
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x00000207FA58EAD0>, 'Connection to hist.databento.com timed out. (connect timeout=100)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='hist.databento.com', port=443): Max retries exceeded with url: /v0/metadata.get_dataset_range?dataset=GLBX.MDP3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000207FA58EAD0>, 'Connection to hist.databento.com timed out. (connect timeout=100)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 42, in get_historical_end_time
    metadata = DATABENTO_CLIENT.metadata.get_dataset_range(dataset=dataset)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\metadata.py", line 254, in get_dataset_range
    response: Response = self._get(
                         ~~~~~~~~~^
        url=self._base_url + ".get_dataset_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        params=params,
        ^^^^^^^^^^^^^^
        basic_auth=True,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 61, in _get
    with requests.get(
         ~~~~~~~~~~~~^
        url=url,
        ^^^^^^^^
    ...<3 lines>...
        timeout=(self.TIMEOUT, self.TIMEOUT),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as response:
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='hist.databento.com', port=443): Max retries exceeded with url: /v0/metadata.get_dataset_range?dataset=GLBX.MDP3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000207FA58EAD0>, 'Connection to hist.databento.com timed out. (connect timeout=100)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 119, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 107, in get_historical_data
    end_time = get_historical_end_time(dataset, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 51, in get_historical_end_time
    safe_historical_end = datetime.now(timezone.utc) - timedelta(minutes=10)
                          ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'?
2025-08-11 23:05:31,512 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:05:56,503 - INFO - Running strategy for /ES at 2025-08-11 16:05:56.503617-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:06:53,159 - ERROR - Error fetching historical end time for dataset GLBX.MDP3: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2025-08-11 23:06:53,160 - ERROR - Error in strategy for /ES: name 'datetime' is not defined
Traceback (most recent call last):
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\ssl_.py", line 460, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\ssl_.py", line 504, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\truststore\_api.py", line 113, in wrap_socket
    ssl_sock = self._ctx.wrap_socket(
        sock,
    ...<4 lines>...
        session=session,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\ssl_.py", line 460, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\ssl_.py", line 504, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\truststore\_api.py", line 113, in wrap_socket
    ssl_sock = self._ctx.wrap_socket(
        sock,
    ...<4 lines>...
        session=session,
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 42, in get_historical_end_time
    metadata = DATABENTO_CLIENT.metadata.get_dataset_range(dataset=dataset)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\metadata.py", line 254, in get_dataset_range
    response: Response = self._get(
                         ~~~~~~~~~^
        url=self._base_url + ".get_dataset_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        params=params,
        ^^^^^^^^^^^^^^
        basic_auth=True,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 61, in _get
    with requests.get(
         ~~~~~~~~~~~~^
        url=url,
        ^^^^^^^^
    ...<3 lines>...
        timeout=(self.TIMEOUT, self.TIMEOUT),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as response:
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 120, in get_historical_and_live_data
    def get_historical_and_live_data(ticker, timeframe, logger, strategy):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 108, in get_historical_data
    end_time = get_historical_end_time(dataset, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 51, in get_historical_end_time
    safe_historical_end = datetime.now(timezone.utc) - timedelta(minutes=10)
                          ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'?
2025-08-11 23:09:55,905 - INFO - Running strategy for /ES at 2025-08-11 16:09:55.905264-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:10:00,534 - ERROR - Error in strategy for /ES: unhashable type: 'dict'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 121, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 115, in get_historical_data
    instrument_id = symbology_resolve(dataset, symbol, start_time, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 81, in symbology_resolve
    print("Resolved symbol: ", {result})
                               ^^^^^^^^
TypeError: unhashable type: 'dict'
2025-08-11 23:10:00,683 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:11:14,076 - INFO - Running strategy for /ES at 2025-08-11 16:11:14.076342-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:11:19,215 - ERROR - Error in strategy for /ES: unhashable type: 'dict'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 120, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 114, in get_historical_data
    instrument_id = symbology_resolve(dataset, symbol, start_time, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 81, in symbology_resolve
    print("Resolved symbol: ", {result})
                               ^^^^^^^^
TypeError: unhashable type: 'dict'
2025-08-11 23:11:19,369 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:14:12,013 - INFO - Running strategy for /ES at 2025-08-11 16:14:12.013580-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:14:21,257 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:20:26,408 - INFO - Running strategy for /ES at 2025-08-11 16:20:26.408304-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:20:31,711 - ERROR - Error in strategy for /ES: 'dict' object has no attribute 'to_df'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 122, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 116, in get_historical_data
    instrument_id = symbology_resolve(dataset, symbol, start_time, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 81, in symbology_resolve
    df = result.to_df()
         ^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'to_df'
2025-08-11 23:20:31,912 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:30:48,441 - INFO - Running strategy for /ES at 2025-08-11 16:30:48.441301-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:30:54,311 - ERROR - Error in strategy for /ES: 'dict' object has no attribute 'to_df'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 121, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 115, in get_historical_data
    instrument_id = symbology_resolve(dataset, symbol, start_time, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 80, in symbology_resolve
    df = result.to_df()
         ^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'to_df'
2025-08-11 23:30:54,459 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:58:03,397 - INFO - Running strategy for /ES at 2025-08-11 16:58:03.397761-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:58:09,229 - ERROR - Error in strategy for /ES: 'dict' object has no attribute 'to_df'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 121, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 115, in get_historical_data
    instrument_id = symbology_resolve(dataset, symbol, start_time, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 80, in symbology_resolve
    df = result.to_df()
         ^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'to_df'
2025-08-11 23:58:09,386 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 23:58:46,000 - INFO - Running strategy for /ES at 2025-08-11 16:58:46.000130-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-11 23:58:50,561 - ERROR - Error in strategy for /ES: 'dict' object has no attribute 'to_df'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 121, in get_historical_and_live_data
    get_historical_data(ticker, timeframe, logger)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 115, in get_historical_data
    instrument_id = symbology_resolve(dataset, symbol, start_time, end_time)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 80, in symbology_resolve
    df = result.to_df()
         ^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'to_df'
2025-08-11 23:58:50,728 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-12 01:26:03,805 - INFO - Running strategy for /ES at 2025-08-11 18:26:03.805886-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 01:26:07,072 - ERROR - Error in strategy for /ES: get_tick_based_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 134, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 128, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, instrument_id, symbol)
TypeError: get_tick_based_data() takes 5 positional arguments but 6 were given
2025-08-12 01:26:07,232 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-12 01:27:57,346 - INFO - Running strategy for /ES at 2025-08-11 18:27:57.346934-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 01:28:03,074 - ERROR - Error in strategy for /ES: get_tick_based_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 134, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 128, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, instrument_id, symbol)
TypeError: get_tick_based_data() takes 5 positional arguments but 6 were given
2025-08-12 01:28:03,366 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-12 01:28:44,493 - INFO - Running strategy for /ES at 2025-08-11 18:28:44.493436-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 01:28:48,760 - ERROR - Error in strategy for /ES: get_tick_based_data() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 134, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 128, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, instrument_id, symbol)
TypeError: get_tick_based_data() takes 5 positional arguments but 6 were given
2025-08-12 01:28:49,472 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-12 01:29:46,961 - INFO - Running strategy for /ES at 2025-08-11 18:29:46.961744-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 01:30:04,184 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-12 01:35:31,720 - INFO - Running strategy for /ES at 2025-08-11 18:35:31.720912-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 01:35:34,547 - ERROR - Error in strategy for /ES: get_tick_based_data() takes 4 positional arguments but 5 were given
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 50, in ema_strategy
    df = get_historical_and_live_data(
        ticker=ticker,
    ...<2 lines>...
        strategy="ema"
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 106, in get_historical_and_live_data
    return get_historical_data(ticker, timeframe, logger)
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 99, in get_historical_data
    df = get_tick_based_data(tick_size, dataset, start_time, end_time, symbol)
TypeError: get_tick_based_data() takes 4 positional arguments but 5 were given
2025-08-12 01:35:35,421 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-12 01:36:10,162 - INFO - Running strategy for /ES at 2025-08-11 18:36:10.162719-04:00 with params: Schwab_QTY=0, Tasty_QTY=0 TRENDS=(1, EMA), (1, EMA)
2025-08-12 01:36:29,068 - ERROR - Error in main loop for /ES: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
