2025-08-08 21:47:56,746 - INFO - Running strategy for /RTY at 2025-08-08 15:47:56.746188-04:00 with params: Schwab_QTY=4, Tasty_QTY=30 TRENDS=(1, EMA), (1, EMA)
2025-08-08 21:47:56,747 - INFO - Using time-based approach for /RTY with 5 timeframe
2025-08-08 21:47:57,508 - ERROR - Error fetching time-based data from Databento: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-08 19:40:00+00:00'. The `end` in the query ('2025-08-08 19:47:56.747836+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
2025-08-08 21:47:57,509 - ERROR - Error in strategy for /RTY: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-08 19:40:00+00:00'. The `end` in the query ('2025-08-08 19:47:56.747836+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 74, in ema_strategy
    df = get_historical_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 359, in get_historical_data
    data = db_client.timeseries.get_range(
  File "C:\Users\csg\AppData\Local\Programs\Python\Python310\lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
  File "C:\Users\csg\AppData\Local\Programs\Python\Python310\lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
  File "C:\Users\csg\AppData\Local\Programs\Python\Python310\lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
databento.common.error.BentoClientError: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-08 19:40:00+00:00'. The `end` in the query ('2025-08-08 19:47:56.747836+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
2025-08-08 21:47:58,323 - ERROR - Error in main loop for /RTY: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 1116, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-08 21:48:36,296 - INFO - Running strategy for /RTY at 2025-08-08 15:48:36.296593-04:00 with params: Schwab_QTY=4, Tasty_QTY=30 TRENDS=(1, EMA), (1, EMA)
2025-08-08 21:48:36,299 - INFO - Using time-based approach for /RTY with 5 timeframe
2025-08-08 21:48:36,746 - ERROR - Error fetching time-based data from Databento: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-08 19:40:00+00:00'. The `end` in the query ('2025-08-08 19:48:36.298205+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
2025-08-08 21:48:36,746 - ERROR - Error in strategy for /RTY: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-08 19:40:00+00:00'. The `end` in the query ('2025-08-08 19:48:36.298205+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 74, in ema_strategy
    df = get_historical_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 361, in get_historical_data
    data = db_client.timeseries.get_range(
  File "C:\Users\csg\AppData\Local\Programs\Python\Python310\lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
  File "C:\Users\csg\AppData\Local\Programs\Python\Python310\lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
  File "C:\Users\csg\AppData\Local\Programs\Python\Python310\lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
databento.common.error.BentoClientError: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-08 19:40:00+00:00'. The `end` in the query ('2025-08-08 19:48:36.298205+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
2025-08-08 21:48:37,467 - ERROR - Error in main loop for /RTY: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 1118, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-08 21:49:44,470 - INFO - Running strategy for /RTY at 2025-08-08 15:49:44.470541-04:00 with params: Schwab_QTY=4, Tasty_QTY=30 TRENDS=(1, EMA), (1, EMA)
2025-08-08 21:49:44,473 - INFO - Using time-based approach for /RTY with 5 timeframe
2025-08-08 21:49:44,904 - ERROR - Error fetching time-based data from Databento: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-08 19:40:00+00:00'. The `end` in the query ('2025-08-08 19:49:44.473230+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
2025-08-08 21:49:44,904 - ERROR - Error in strategy for /RTY: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-08 19:40:00+00:00'. The `end` in the query ('2025-08-08 19:49:44.473230+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 74, in ema_strategy
    df = get_historical_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 362, in get_historical_data
    data = db_client.timeseries.get_range(
  File "C:\Users\csg\AppData\Local\Programs\Python\Python310\lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
  File "C:\Users\csg\AppData\Local\Programs\Python\Python310\lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
  File "C:\Users\csg\AppData\Local\Programs\Python\Python310\lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
databento.common.error.BentoClientError: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-08 19:40:00+00:00'. The `end` in the query ('2025-08-08 19:49:44.473230+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
2025-08-08 21:49:45,748 - ERROR - Error in main loop for /RTY: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 1119, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-08 22:28:24,546 - INFO - Running strategy for /RTY at 2025-08-08 16:28:24.546862-04:00 with params: Schwab_QTY=4, Tasty_QTY=30 TRENDS=(1, EMA), (1, EMA)
2025-08-08 22:28:24,549 - INFO - Using time-based approach for /RTY with 5 timeframe
2025-08-08 22:28:25,297 - ERROR - Error fetching time-based data from Databento: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-08 20:20:00+00:00'. The `end` in the query ('2025-08-08 20:28:24.547689+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
2025-08-08 22:28:25,312 - ERROR - Error in strategy for /RTY: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-08 20:20:00+00:00'. The `end` in the query ('2025-08-08 20:28:24.547689+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 74, in ema_strategy
    df = get_historical_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 363, in get_historical_data
    data = db_client.timeseries.get_range(
  File "C:\Users\csg\AppData\Local\Programs\Python\Python310\lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
  File "C:\Users\csg\AppData\Local\Programs\Python\Python310\lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
  File "C:\Users\csg\AppData\Local\Programs\Python\Python310\lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
databento.common.error.BentoClientError: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-08 20:20:00+00:00'. The `end` in the query ('2025-08-08 20:28:24.547689+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
2025-08-08 22:28:26,110 - ERROR - Error in main loop for /RTY: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 1120, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-08 22:28:46,881 - INFO - Running strategy for /RTY at 2025-08-08 16:28:46.881894-04:00 with params: Schwab_QTY=4, Tasty_QTY=30 TRENDS=(1, EMA), (1, EMA)
2025-08-08 22:28:46,886 - INFO - Using time-based approach for /RTY with 5 timeframe
2025-08-08 22:28:47,295 - ERROR - Error fetching time-based data from Databento: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-08 20:20:00+00:00'. The `end` in the query ('2025-08-08 20:28:46.882419+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
2025-08-08 22:28:47,371 - ERROR - Error in strategy for /RTY: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-08 20:20:00+00:00'. The `end` in the query ('2025-08-08 20:28:46.882419+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 74, in ema_strategy
    df = get_historical_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 363, in get_historical_data
    data = db_client.timeseries.get_range(
  File "C:\Users\csg\AppData\Local\Programs\Python\Python310\lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
  File "C:\Users\csg\AppData\Local\Programs\Python\Python310\lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
  File "C:\Users\csg\AppData\Local\Programs\Python\Python310\lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
databento.common.error.BentoClientError: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-08 20:20:00+00:00'. The `end` in the query ('2025-08-08 20:28:46.882419+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
2025-08-08 22:28:48,090 - ERROR - Error in main loop for /RTY: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 1120, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-09 00:38:17,200 - INFO - Running strategy for /RTY at 2025-08-08 18:38:17.200570-04:00 with params: Schwab_QTY=4, Tasty_QTY=30 TRENDS=(1, EMA), (1, EMA)
2025-08-09 00:38:21,247 - ERROR - Error in strategy for /RTY: Unsupported timeframe: 5
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 76, in ema_strategy
    df = get_historical_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 159, in get_historical_data
    raise ValueError(f"Unsupported timeframe: {timeframe}")
ValueError: Unsupported timeframe: 5
2025-08-09 00:46:20,581 - ERROR - Error in strategy for /RTY: name 'get_strategy_prarams' is not defined
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 14, in ema_strategy
    ] = get_strategy_prarams("ema", ticker, logger)
NameError: name 'get_strategy_prarams' is not defined
2025-08-09 00:50:35,661 - ERROR - Error in strategy for /RTY: name 'get_strategy_prarams' is not defined
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 14, in ema_strategy
    ] = get_strategy_prarams("ema", ticker, logger)
NameError: name 'get_strategy_prarams' is not defined
2025-08-09 00:51:07,710 - ERROR - Error in strategy for /RTY: name 'get_strategy_prarams' is not defined
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 15, in ema_strategy
    ] = get_strategy_prarams("ema", ticker, logger)
NameError: name 'get_strategy_prarams' is not defined
2025-08-11 02:18:23,747 - INFO - Running strategy for /RTY at 2025-08-10 20:18:23.747076-04:00 with params: Schwab_QTY=4, Tasty_QTY=30 TRENDS=(1, EMA), (1, EMA)
2025-08-11 02:18:27,795 - ERROR - Error in strategy for /RTY: Unsupported timeframe: 5
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 54, in ema_strategy
    df = get_historical_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 159, in get_historical_data
    raise ValueError(f"Unsupported timeframe: {timeframe}")
ValueError: Unsupported timeframe: 5
2025-08-11 02:18:28,191 - ERROR - Error in main loop for /RTY: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 02:19:56,422 - INFO - Running strategy for /RTY at 2025-08-10 20:19:56.422181-04:00 with params: Schwab_QTY=4, Tasty_QTY=30 TRENDS=(1, EMA), (1, EMA)
2025-08-11 02:20:00,474 - ERROR - Error in strategy for /RTY: Unsupported timeframe: 5
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\ema_strategy.py", line 56, in ema_strategy
    df = get_historical_data(
  File "D:\sde\Tim\tasty-schwab-trader-BE\get_historical_data.py", line 159, in get_historical_data
    raise ValueError(f"Unsupported timeframe: {timeframe}")
ValueError: Unsupported timeframe: 5
2025-08-11 02:20:00,877 - ERROR - Error in main loop for /RTY: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\sde\Tim\tasty-schwab-trader-BE\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 06:00:05,476 - INFO - Running strategy for /RTY at 2025-08-10 23:00:05.476094-04:00 with params: Schwab_QTY=4, Tasty_QTY=30 TRENDS=(1, EMA), (1, EMA)
2025-08-11 06:00:07,639 - ERROR - Error in strategy for /RTY: Unsupported timeframe: 5
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 53, in ema_strategy
    df = get_historical_data(
        ticker,
        timeframe,
        logger=logger,
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 159, in get_historical_data
    raise ValueError(f"Unsupported timeframe: {timeframe}")
ValueError: Unsupported timeframe: 5
2025-08-11 06:00:08,809 - ERROR - Error in main loop for /RTY: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 06:16:43,921 - INFO - Running strategy for /RTY at 2025-08-10 23:16:43.921068-04:00 with params: Schwab_QTY=4, Tasty_QTY=30 TRENDS=(1, EMA), (1, EMA)
2025-08-11 06:16:45,954 - ERROR - Error in strategy for /RTY: Unsupported timeframe: 5
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 53, in ema_strategy
    df = get_historical_data(
        ticker,
        timeframe,
        logger=logger,
    )
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 159, in get_historical_data
    raise ValueError(f"Unsupported timeframe: {timeframe}")
ValueError: Unsupported timeframe: 5
2025-08-11 06:16:46,239 - ERROR - Error in main loop for /RTY: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 09:58:47,308 - INFO - Running strategy for /RTY at 2025-08-11 02:58:47.308050-04:00 with params: Schwab_QTY=4, Tasty_QTY=30 TRENDS=(1, EMA), (1, EMA)
2025-08-11 09:58:49,599 - INFO - Resolved symbol: {'result': {'RTYU5': [{'d0': '2025-08-06', 'd1': '2025-08-12', 's': '42003082'}]}, 'symbols': ['RTYU5'], 'stype_in': 'raw_symbol', 'stype_out': 'instrument_id', 'start_date': '2025-08-06', 'end_date': '2025-08-12', 'partial': [], 'not_found': [], 'message': 'OK', 'status': 0}
2025-08-11 09:58:50,718 - ERROR - Error getting historical data for /RTY: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-11 06:50:00+00:00'. The `end` in the query ('2025-08-11 06:58:48.112739+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 184, in get_time_based_historical_data
    # Get historical data
           ^^^^^^^^^^^^^^
    ...<5 lines>...
        end=end_date
    
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-11 06:50:00+00:00'. The `end` in the query ('2025-08-11 06:58:48.112739+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
2025-08-11 09:58:50,735 - ERROR - Error in strategy for /RTY: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 60, in ema_strategy
    df["trend1"] = df["close"].ewm(span=int(period_1)).mean()
                   ~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2025-08-11 09:58:50,898 - ERROR - Error in main loop for /RTY: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 10:03:46,935 - INFO - Running strategy for /RTY at 2025-08-11 03:03:46.935317-04:00 with params: Schwab_QTY=4, Tasty_QTY=30 TRENDS=(1, EMA), (1, EMA)
2025-08-11 10:03:54,075 - INFO - Resolved symbol: {'result': {'RTYU5': [{'d0': '2025-08-06', 'd1': '2025-08-12', 's': '42003082'}]}, 'symbols': ['RTYU5'], 'stype_in': 'raw_symbol', 'stype_out': 'instrument_id', 'start_date': '2025-08-06', 'end_date': '2025-08-12', 'partial': [], 'not_found': [], 'message': 'OK', 'status': 0}
2025-08-11 10:03:55,534 - ERROR - Error getting historical data for /RTY: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-11 07:00:00+00:00'. The `end` in the query ('2025-08-11 07:03:52.853866+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 194, in get_time_based_historical_data
    data = db_client.timeseries.get_range(
        dataset=dataset,
    ...<3 lines>...
        end=end_date
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-11 07:00:00+00:00'. The `end` in the query ('2025-08-11 07:03:52.853866+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
2025-08-11 10:03:55,539 - ERROR - Error in strategy for /RTY: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 60, in ema_strategy
    df["trend1"] = df["close"].ewm(span=int(period_1)).mean()
                   ~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2025-08-11 10:03:55,709 - ERROR - Error in main loop for /RTY: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 10:10:24,616 - INFO - Running strategy for /RTY at 2025-08-11 03:10:24.616307-04:00 with params: Schwab_QTY=4, Tasty_QTY=30 TRENDS=(1, EMA), (1, EMA)
2025-08-11 10:10:27,166 - INFO - Resolved symbol: {'result': {'RTYU5': [{'d0': '2025-08-06', 'd1': '2025-08-12', 's': '42003082'}]}, 'symbols': ['RTYU5'], 'stype_in': 'raw_symbol', 'stype_out': 'instrument_id', 'start_date': '2025-08-06', 'end_date': '2025-08-12', 'partial': [], 'not_found': [], 'message': 'OK', 'status': 0}
2025-08-11 10:10:28,342 - ERROR - Error getting historical data for /RTY: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-11 07:10:00+00:00'. The `end` in the query ('2025-08-11 07:10:25.298881+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 188, in get_time_based_historical_data
    data = db_client.timeseries.get_range(
        dataset=dataset,
    ...<3 lines>...
        end=end_date
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-11 07:10:00+00:00'. The `end` in the query ('2025-08-11 07:10:25.298881+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
2025-08-11 10:10:28,392 - ERROR - Error in strategy for /RTY: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 60, in ema_strategy
    df["trend1"] = df["close"].ewm(span=int(period_1)).mean()
                   ~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2025-08-11 10:10:28,543 - ERROR - Error in main loop for /RTY: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 10:11:12,094 - INFO - Running strategy for /RTY at 2025-08-11 03:11:12.094150-04:00 with params: Schwab_QTY=4, Tasty_QTY=30 TRENDS=(1, EMA), (1, EMA)
2025-08-11 10:11:14,761 - INFO - Resolved symbol: {'result': {'RTYU5': [{'d0': '2025-08-06', 'd1': '2025-08-12', 's': '42003082'}]}, 'symbols': ['RTYU5'], 'stype_in': 'raw_symbol', 'stype_out': 'instrument_id', 'start_date': '2025-08-06', 'end_date': '2025-08-12', 'partial': [], 'not_found': [], 'message': 'OK', 'status': 0}
2025-08-11 10:11:16,027 - ERROR - Error getting historical data for /RTY: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-11 07:10:00+00:00'. The `end` in the query ('2025-08-11 07:11:12.913898+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 190, in get_time_based_historical_data
    data = db_client.timeseries.get_range(
        dataset=dataset,
    ...<3 lines>...
        end=end_date
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-11 07:10:00+00:00'. The `end` in the query ('2025-08-11 07:11:12.913898+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
2025-08-11 10:11:16,032 - ERROR - Error in strategy for /RTY: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 60, in ema_strategy
    df["trend1"] = df["close"].ewm(span=int(period_1)).mean()
                   ~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2025-08-11 10:11:16,188 - ERROR - Error in main loop for /RTY: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 10:12:03,830 - INFO - Running strategy for /RTY at 2025-08-11 03:12:03.830169-04:00 with params: Schwab_QTY=4, Tasty_QTY=30 TRENDS=(1, EMA), (1, EMA)
2025-08-11 10:12:05,549 - INFO - Resolved symbol: {'result': {'RTYU5': [{'d0': '2025-08-06', 'd1': '2025-08-12', 's': '42003082'}]}, 'symbols': ['RTYU5'], 'stype_in': 'raw_symbol', 'stype_out': 'instrument_id', 'start_date': '2025-08-06', 'end_date': '2025-08-12', 'partial': [], 'not_found': [], 'message': 'OK', 'status': 0}
2025-08-11 10:12:06,819 - ERROR - Error getting historical data for /RTY: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-11 07:10:00+00:00'. The `end` in the query ('2025-08-11 07:12:04.181852+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 190, in get_time_based_historical_data
    data = db_client.timeseries.get_range(
        dataset=dataset,
    ...<3 lines>...
        end=end_date
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-11 07:10:00+00:00'. The `end` in the query ('2025-08-11 07:12:04.181852+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
2025-08-11 10:12:06,823 - ERROR - Error in strategy for /RTY: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 60, in ema_strategy
    df["trend1"] = df["close"].ewm(span=int(period_1)).mean()
                   ~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2025-08-11 10:12:06,986 - ERROR - Error in main loop for /RTY: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 10:54:00,463 - INFO - Running strategy for /RTY at 2025-08-11 03:54:00.463670-04:00 with params: Schwab_QTY=4, Tasty_QTY=30 TRENDS=(1, EMA), (1, EMA)
2025-08-11 10:54:00,463 - INFO - Running strategy for /RTY at 2025-08-11 03:54:00.463670-04:00 with params: Schwab_QTY=4, Tasty_QTY=30 TRENDS=(1, EMA), (1, EMA)
2025-08-11 10:54:02,418 - INFO - Resolved symbol: {'result': {'RTYU5': [{'d0': '2025-08-06', 'd1': '2025-08-12', 's': '42003082'}]}, 'symbols': ['RTYU5'], 'stype_in': 'raw_symbol', 'stype_out': 'instrument_id', 'start_date': '2025-08-06', 'end_date': '2025-08-12', 'partial': [], 'not_found': [], 'message': 'OK', 'status': 0}
2025-08-11 10:54:02,418 - INFO - Resolved symbol: {'result': {'RTYU5': [{'d0': '2025-08-06', 'd1': '2025-08-12', 's': '42003082'}]}, 'symbols': ['RTYU5'], 'stype_in': 'raw_symbol', 'stype_out': 'instrument_id', 'start_date': '2025-08-06', 'end_date': '2025-08-12', 'partial': [], 'not_found': [], 'message': 'OK', 'status': 0}
2025-08-11 10:54:03,773 - ERROR - Error getting historical data for /RTY: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-11 07:50:00+00:00'. The `end` in the query ('2025-08-11 07:54:00.870087+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 190, in get_time_based_historical_data
    if data is None:
           ^^^^^^^^^
    ...<5 lines>...
    if df.empty:
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-11 07:50:00+00:00'. The `end` in the query ('2025-08-11 07:54:00.870087+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
2025-08-11 10:54:03,773 - ERROR - Error getting historical data for /RTY: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-11 07:50:00+00:00'. The `end` in the query ('2025-08-11 07:54:00.870087+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 190, in get_time_based_historical_data
    if data is None:
           ^^^^^^^^^
    ...<5 lines>...
    if df.empty:
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-11 07:50:00+00:00'. The `end` in the query ('2025-08-11 07:54:00.870087+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
2025-08-11 10:54:03,777 - ERROR - Error in strategy for /RTY: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 60, in ema_strategy
    df["trend1"] = df["close"].ewm(span=int(period_1)).mean()
                   ~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2025-08-11 10:54:03,777 - ERROR - Error in strategy for /RTY: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 60, in ema_strategy
    df["trend1"] = df["close"].ewm(span=int(period_1)).mean()
                   ~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2025-08-11 10:54:03,962 - ERROR - Error in main loop for /RTY: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 10:54:03,962 - ERROR - Error in main loop for /RTY: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
2025-08-11 11:15:18,978 - INFO - Running strategy for /RTY at 2025-08-11 04:15:18.978016-04:00 with params: Schwab_QTY=4, Tasty_QTY=30 TRENDS=(1, EMA), (1, EMA)
2025-08-11 11:15:22,048 - INFO - Resolved symbol: {'result': {'RTYU5': [{'d0': '2025-08-06', 'd1': '2025-08-12', 's': '42003082'}]}, 'symbols': ['RTYU5'], 'stype_in': 'raw_symbol', 'stype_out': 'instrument_id', 'start_date': '2025-08-06', 'end_date': '2025-08-12', 'partial': [], 'not_found': [], 'message': 'OK', 'status': 0}
2025-08-11 11:15:23,188 - ERROR - Error getting historical data for /RTY: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-11 08:10:00+00:00'. The `end` in the query ('2025-08-11 08:15:19.931840+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\get_historical_data.py", line 181, in get_time_based_historical_data
    data = db_client.timeseries.get_range(
        dataset=dataset,
    ...<3 lines>...
        end=end_date
    )
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\historical\api\timeseries.py", line 125, in get_range
    return self._stream(
           ~~~~~~~~~~~~^
        url=self._base_url + ".get_range",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        path=path,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 134, in _stream
    check_http_error(response)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Super\AppData\Local\Programs\Python\Python313\Lib\site-packages\databento\common\http.py", line 249, in check_http_error
    raise BentoClientError(
    ...<5 lines>...
    )
databento.common.error.BentoClientError: 422 data_end_after_available_end
The dataset GLBX.MDP3 has data available up to '2025-08-11 08:10:00+00:00'. The `end` in the query ('2025-08-11 08:15:19.931840+00:00') is after the available range. Try requesting with an earlier `end`.
documentation: https://databento.com/docs/api-reference-historical/basics/datasets
2025-08-11 11:15:23,192 - ERROR - Error in strategy for /RTY: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\ema_strategy.py", line 60, in ema_strategy
    df["trend1"] = df["close"].ewm(span=int(period_1)).mean()
                   ~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2025-08-11 11:15:23,361 - ERROR - Error in main loop for /RTY: get_strategy_prarams() missing 1 required positional argument: 'logger'
Traceback (most recent call last):
  File "D:\work\work\Tim McKenna\Tim\backend\main_equities.py", line 46, in main_strategy_loop
    [timeframe, *_] = get_strategy_prarams(ticker, logger)
                      ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: get_strategy_prarams() missing 1 required positional argument: 'logger'
